### ISSUE TITLE
Add a remove ticket function

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#114]
It would be nice if you could delete a ticket. So you can make a test purchase and later remove it.

**Comment by treed593** [comment]
Also, the ability to Un-Chek-In a ticket that you are using for testing

**Comment by BunsenMcDubbs** [comment]
Not only for testing but just in general/production being able to remove/refund purchases and un-checking-in attendees (if volunteers accidentally marked the wrong person etc)

**Comment by cbellone** [comment]
partially implemented (see #195), postponed to 1.10

**Comment by mg-1999** [comment]
1.10 is released, but this wasnt added.

Any update on this?

**Comment by cbellone** [comment]
Hi @mg-1999,

yes. Unfortunately we had to postpone a couple of issues, because the work on https://github.com/exteso/alf.io-PI (offline check-in and label printing) took more than expected.

The good news is that there is an user willing to implement it and to send a PR. If we receive the PR from him we'll release a minor version (1.10.x) soon.

We'll keep you posted. Thank you!

**Comment by syjer** [comment]
nearly done.

TODO:

 - [ ] refund support
 - [ ] cleanup ui/ux
 - [ ] set reservation to status 'CANCELLED' when tickets count = 0
 - [ ] add option to send an email to the tickets owner
 - [ ] ?

**Comment by syjer** [comment]
finally done.

**Comment by mg-1999** [comment]
Awesome! Was looking forward to this one :)
