### ISSUE TITLE
Event creation issue with 1.7.3

### ISSUE THREAD

**Issue by juliusdev** [exteso/alf.io#124]
Hi, 

I failed to create new paid event in the admin with currency $ or €. No errors messages are displayed, but the check API return json error : 

 {"validationErrors":[{"fieldName":"currency","message":"error.currency"},{"fieldName":"currency","message":"error.currency"}],"errorCount":2,"success":false}

it's bug ?

![capture d ecran 2016-05-12 a 16 28 01](https://cloud.githubusercontent.com/assets/930674/15218134/c95c7362-185e-11e6-8f03-efe222463658.png)

**Comment by cbellone** [comment]
Hi @juliusdev,

And thank you for using alf.io!

You should insert the 3 char ISO code of your currency, e.g. USD or EUR

The error feedback will be fixed as soon as we'll rewrite the admin GUI
(most likely v. 1.9)

Enjoy alf.io!
Celestino
Il 12-mag-2016 4:31 PM, "juliusdev" <notifications@github.com> ha scritto:

Hi,

I failed to create new paid event in the admin with currency $ or €. No
errors messages are displayed, but the check API return json error :

{"validationErrors":[{"fieldName":"currency","message":"error.currency"},{"fieldName":"currency","message":"error.currency"}],"errorCount":2,"success":false}

it's bug ?

[image: capture d ecran 2016-05-12 a 16 28 01]
<https://cloud.githubusercontent.com/assets/930674/15218134/c95c7362-185e-11e6-8f03-efe222463658.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/exteso/alf.io/issues/124>

**Comment by juliusdev** [comment]
Thanks
