### ISSUE TITLE
backend Android app:  login failure

### ISSUE THREAD

**Issue by kwdebr** [exteso/alf.io#125]
Hi Celestino

Next school year we plan to use Alf.io for the organization of different school concerts by students and teachers.  We would also like to use the newly developed backend Android app.  I downloaded it on my smartphone but I get an error when I try to login:  "Unexpected Error"  "Error during data loading.  Check internet connectivity and retry". 

Are you aware of this problem?  Any advize on what we might be doing wrong?  Or is it still a bug in the code?

Otherwise, we are very happy with your project and we would be most willing to give you further feedback on how it works for us.

Best regards

Kurt
Academy of Performing Arts Roeselare, Belgium

**Comment by cbellone** [comment]
Hi Kurt,

that's great news! Thank you for using alf.io!

As far as I know, the mobile app should be feature complete and stable enough. We used the latest version a couple of weeks ago to check-in ~330 attendees and everything went fine.

I have a couple of questions for you, in order to understand what's going on:

- is your alf.io instance accessible from the phone? (i.e. can you open the reservation page using the browser on the phone?)
- did you scan the QR code or did you insert the account manually?  
- For security reasons, you can access alf.io from the mobile app only using a non-privileged account. Is your user a "Check-in operator" or a "Sponsor"? Otherwise access will be denied.

We know that there is a lack in the documentation for the mobile app, it would be great if you could contribute to that! :-)

Thanks
Celestino

**Comment by cbellone** [comment]
closed for inactivity
