### ISSUE TITLE
Getting "invalid API key", not sure which one

### ISSUE THREAD

**Issue by kasbah** [exteso/alf.io#126]
Hey, thanks for making alf.io!

I set up alf.io on Openshift and am trying to add a test event.

I didn't really want to add a maps API because all our events are in the same place anyway so I was trying to leave it blank, but it wouldn't allow it. So I put in a '0' which let me go ahead at least. (Similarily I didn't want to create an organization, since we are just one organization--but I had to). 

I can't create my first event though it just ends up saying 'Invalid API key' in the top right. I since added Stripe and Mailgun APIs and also ended up getting Maps API keys to see if it would fix it. Anyway it still just says 'Invalid API key', not sure which API it is referrring to at this point. 

In the console:

```
13:35:08.650 Content Security Policy: The page's settings blocked the loading of a resource at self ("style-src https://events-bristolhackspace.rhcloud.com").1 admin
13:35:41.955 Invalid API key.1 angular.min.js:102:264
```

**Comment by cbellone** [comment]
Hi @kasbah,

thanks for using alf.io! And thank you very much for your feedback! :-)

Here below my answers:

> I didn't really want to add a maps API because all our events are in the same place anyway so I was trying to leave it blank, but it wouldn't allow it. So I put in a '0' which let me go ahead at least. 

the Google API Keys (client and server) are required in order to retrieve the location timezone and display the event map. See https://github.com/exteso/alf.io/issues/76 for the detailed information about which service you should enable.
We are thinking about simplifying the setup/event creation processes so any input/suggestion/help in this regard would be highly appreciated.

> Similarily I didn't want to create an organization, since we are just one organization--but I had to.

You must create at least an organization, because alf.io will use its data while sending e-mails and on the event website itself.

> I can't create my first event though it just ends up saying 'Invalid API key' in the top right.

see above, I think that there is something missing in the Google Maps configuration

**Comment by kasbah** [comment]
OK, I enabled "Google Maps Time Zone API" and "Google Static Maps API" which where disabled. Double checked the keys are copied correctly but still getting the error. It happens when I click the time-zone field actually and there is nothing to select in that field. 

You might like to check how [Attendize](https://github.com/attendize/attendize) does it. I was testing that as well and the maps/address stuff just works without setting up a key.

**Comment by cbellone** [comment]
Hi @kasbah 

> OK, I enabled "Google Maps Time Zone API" and "Google Static Maps API" which were disabled. Double checked the keys are copied correctly but still getting the error.

you, as admin, can override the same value for an option also at organization level (and event level, once you create an event). Could you please check in the configuration for overrides?

Otherwise please do the following: create a new user with the "organization owner" role under your organization and send me the authentication details (along with the address of your installation) via pm on twitter https://twitter.com/c_bellone

> You might like to check how Attendize does it. I was testing that as well and the maps/address stuff just works without setting up a key.

As per Google's T&C, you can omit the key only if you're running a public accessible service. So if you use alf.io for your private events and access it in your company's LAN, you're breaking the T&C.

But I do agree that google keys shouldn't be required to run alf.io. I will open an issue for that. Thank you!

**Comment by cbellone** [comment]
closed. See #127
