### ISSUE TITLE
The manual "Check-In" button only appears when there's a single match

### ISSUE THREAD

**Issue by alberanid** [exteso/alf.io#196]
If I'm not wrong, you have to restrict the filter so that a single result is matched, to make the "Check-In" button appear.

This may not always be so simple (think about homonymous people) to do.

Possible improvements that deserves their own issue:

- a "mass check-in" (with a series of checkboxes) would be nice to have.
- a "group check-in" of all the tickets bought in the same reservation.

**Comment by cbellone** [comment]
Yes, that's a problem of the current implementation. Since we're very close to the 1.8 release I would only remove the "single result" check, so that check-in would be possible even if there are more matches for a query.

Btw during the registration of our events we use the manual check-in only as "last resort". Did you take a look to our Android "backoffice" app?

stable version: https://play.google.com/store/apps/details?id=alfio.backoffice
beta (expected release: next week): https://play.google.com/apps/testing/alfio.backoffice

as per the other improvements, could you please open other issues explaining how should they work? Then we'll discuss them one by one.

Thanks!!
