### ISSUE TITLE
Japanese characters in iOS App are garbled characters

### ISSUE THREAD

**Issue by ui2-narita** [exteso/alf.io#302]
Japanese characters in iOS App are garbled.

Can you fix it?

It's a very good solution, so I'd like to try it in Japan as well.

![img_1808](https://user-images.githubusercontent.com/19811193/27844721-5d206bb2-6160-11e7-9e8f-f423fa1efe7b.PNG)

**Comment by cbellone** [comment]
Hi @ui2-narita,
thanks for the bug report! I have opened another issue (https://github.com/exteso/Alf.ioBackoffice/issues/13) in the app repo for that.

**Could you please add there the exact text that you're not seeing, so that we can reproduce the problem?** Thank you very much for that!

We think that It could have something to do with the font used by the app itself. In fact, we think that other functionalities , such as the PDF-ticket, could be affected too. Did you find any other problems? **Could you please generate a ticket and test if everything is displayed correctly on the PDF?**

Thank you very much for your help!

**Comment by ui2-narita** [comment]
Hi cbellone 
Thank you for reply.

PDF was solved by adding Japanese fonts.

The problem is iOS App.
I get json data of Content-type application/json; charset=utf-8 from the server, but iOS App seems to be garbled because the encoding is Latin.

UTF-8 (Japanese)   "2017夏講習"  ->  Latin "2017å¤è¬›ç¿’"

Thank you for your help.

**Comment by cbellone** [comment]
Thanks to @syjer the problem should now be fixed. Here's the preview of the new version. 

We'll submit the app for review next week

![2017-08-05](https://user-images.githubusercontent.com/3385346/28997735-14153dce-7a1c-11e7-85a7-44ca63ef854d.jpg)

Celestino

**Comment by ui2-narita** [comment]
Wow!!
Thank you very much.

I am looking forward to the release.

**Comment by cbellone** [comment]
Just received confirmation that the new version (2.1) of the app has been approved by apple and is ready for download https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1203898610&mt=8
I think it's safe to close this issue

**Comment by NARH** [comment]
I confirmed the release.
Japanese fonts can be displayed without problems.

Thank you very much.
