### ISSUE TITLE
support waiting queue

### ISSUE THREAD

**Issue by syjer** [exteso/alf.io#39]
For those that were not able to buy a ticket. 

If the organizer decide to add more places and/or somebody decide to free up his place, those that are in the queue could have a chance to get them before everybody else.

**Comment by mfirry** [comment]
+1

**Comment by cbellone** [comment]
We could have two kinds of waiting queues:

1) pre-sales
2) after sold-out

1) PRE-SALES
Prerequisites:
- we should have an additional attribute on TicketReservation in order to recognize if a reservation is automatic or not

The user would have the possibility to register him/herself BEFORE the start of sale period. It would be required to give his/her e-mail address.
The logic of the list is "first come first serve".
x hours (configurable) before the sale opening, the user will receive a link to an "automatic" reservation which will expire in x hours (configurable).
If there will be more people in the waiting list than the actual capacity, then the remaining user will receive a link only if a previous sent link would expire.

2) AFTER SOLD-OUT
the user can register him/herself (see above) and if a ticket will become available, he/she would receive a link to an automatic reservation.

**Comment by cbellone** [comment]
done :-)
