### ISSUE TITLE
How to use Alf.io

### ISSUE THREAD

**Issue by royboymaps** [exteso/alf.io#51]
Hi, I know this is not the right place to be asking this, but I honestly cannot find information anywhere else. Alf.io looks like brilliant software and I would love to use it on my website. I'm just wondering, how do I install it? I cannot find instructions anywhere, or even information on where to get instructions or help.

Sorry again for putting this message here but it is honestly a last resort me. Thank you in advance for any help, I greatly appreciate it.

**Comment by cbellone** [comment]
Hi @royboymaps ,
thanks for your interest in alf.io! Don't worry about the channel, the setup of a mailing list is in the pipeline but not yet done! :-)

Yes, you're right, we didn't write enough documentation so far. That's because we are focused on the development and we would need help for this task. But since you're interested in installing and (maybe) using it, what about writing you something and contributing back to the project? It would be great!

To answer your question:
Currently we installed alf.io on PROD instances only on openshift, you can find a step-by-step tutorial here: http://alf.io/tutorials/openshift/ . You can test it using their free-of-charge plan and small gears.
However you could try to run it directly on your own server, if you want. 
For that you'd need a running Postgresql database and jdk8 already installed:
 
java -jar alfio-spring-boot.war \
-Ddatasource.dialect=PGSQL \
-Ddatasource.driver=org.postgresql.Driver \
-Ddatasource.url=jdbc:postgresql://dbhost:dbport/alfio \
-Ddatasource.username=username \
-Ddatasource.password=password \
-Ddatasource.validationQuery=SELECT 1

please note that this approach would expose your database password machine-wide, since it would be part of the process command line. Starting from next release (I'm opening a ticket about that right now) it will be possible to create a datasource.properties file in the same directory, in order to keep secrets actually secret :-)

Should you have questions, please feel free to ask

thank you for using alf.io!
Celestino

**Comment by royboymaps** [comment]
Thank You Celestino,

I will have a look at it and try the openshift version first, then try on my own server. Unfortunately I wouldn't know enough to help out with development in any way, but if I can get it working successfully for me, I would certainly have no problem with helping out with putting together some documentation for it. From looking at the website and the wiki page, it seems to have all the features I could even think of. Thanks again, Roy.

**Comment by cbellone** [comment]
Hi Roy,
I'm closing this task because we created a mailing list https://groups.google.com/d/forum/alfio
Should you have further questions, please post a message there.
Thank you
Celestino

**Comment by flexwie** [comment]
I wrote a little gist on how to set up Alf.io manually.
As I am not a professional and no native english speaker I could use some help on how to install a LetsEncyrpt SSL certificate, how to configure Postfix to be the SMTP server and a general check for mistakes and wording!

https://gist.github.com/flexwie/a8572e8e7ef06ae844925ec857fa3b5b

**Comment by cbellone** [comment]
Hi @flexwie ,

this is fantastic! Thank you for your work!

It would be great if we could create a tutorial page out of it (e.g. like we did for [heroku](https://alf.io/tutorials/heroku/)). Would you be interested in helping with that?

In the meantime, I'll add some comments on the Gist.

Thank you again!!
Celestino

**Comment by flexwie** [comment]
@cbellone, thanks for your comment! I would really appreciate it if you could answer the one open question I just added.

I would love to help create a tutorial page! You just need tell me what to do as I am quite a newbie to open source collaboration ;)

**Comment by cbellone** [comment]
> I would love to help create a tutorial page! 

that's great, thank you! :+1: 

> You just need tell me what to do as I am quite a newbie to open source collaboration ;)

of course! Please join our mailing list https://groups.google.com/d/forum/alfio - we can discuss about it there
