### ISSUE TITLE
improve instructions on location of custom.jvmargs

### ISSUE THREAD

**Issue by jbayer** [exteso/alf.io#63]
i was trying the cloud foundry instructions. when i was trying to set the MAPS_SERVER_API_KEY it wasn't clear where the custom.jvmargs file should be created. when using spring boot it didn't just seem to automatically pick it up when it was set as an app env var, which would have been nice.

what is the best way to set that value when using cloud foundry?

**Comment by cbellone** [comment]
Hi @jbayer,

Thank you for trying alf.io (and also for your suggestions on twitter)

The file custom.jvmargs could come in handy during development, when you have to start the application locally from the command line. It shouldn't be needed while installing on a paas.

Anyway you can set all the properties (google maps keys and e-mail settings are mandatory) on the YOUR-APP.cfapps.io/admin/, under the "Configuration" section.

We'll add a tutorial about the "first run" asap, but first we would like to redesign the "settings" interface, in order to make it more clear and usable. It should be done before releasing the version 1.5

Hope that this could help...
Celestino

**Comment by jbayer** [comment]
makes sense, thanks for the answer!
