### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#78]
How do I add a new language, because I would like to translate this project to Dutch.

**Comment by cbellone** [comment]
Hi @mg-1999 

that's great!

you have to add two new files under 

https://github.com/exteso/alf.io/tree/master/src/main/resources/alfio/i18n

```
public_nl.properties  <-- public website translation
admin_nl.properties  <-- admin area translation
```

then you can test the new translations by adding the new language:

https://github.com/exteso/alf.io/blob/master/src/main/java/alfio/model/ContentLanguage.java

```java
public static final ContentLanguage DUTCH = new ContentLanguage(new Locale("nl"),   0b1000, new Locale("nl"));
```
then add it to the list of available languages:
```java
public static final List<ContentLanguage> ALL_LANGUAGES = Arrays.asList(ITALIAN, ENGLISH, GERMAN, DUTCH);
```
and then build and run the application from the command line (see README)

please note that the Java ResourceBundle utility requires the files to be latin-1 (ISO-8859-1) encoded, otherwise you cannot see special characters like öàä.

Before adding the new files, you can also run the following command:
```
$ $JDK_HOME/bin/native2ascii public_nl.properties > public_nl_new.properties
```
and then swap the files. Do not redirect the output to the original file, otherwise you'll lose all the content!

looking forward to integrating the new language in the 1.6 version! :-)

**Comment by cbellone** [comment]
Fixed, thank you!
