### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by rudboruah** [exteso/alf.io#94]
Hey Guys,

I installed the latest version of your awesome tool just now in Pivotal. All looks good. Error handling still need to be worked on but the basic functionality has impressed me. Well done guys;) 

Questions are: 
- Can we have a Search Feature in the homepage? Angular/ Solr etc?
- Do we have any caching technology being used to handle multiple views for a high volume site?

Cheers,
Rud

**Comment by rudboruah** [comment]
Also, do we have any caching technology being used to handle multiple views for a high volume site?

**Comment by cbellone** [comment]
Hi Rud,

thanks for using alf.io!

yes, the UI/UX in the admin section needs to be improved, the current plan is to rewrite it completely in the next releases (see #59 ). 

Back to your questions:

* Can we have a Search Feature in the homepage? Angular/ Solr etc?
    * I am not sure I understand the question: what do you mean by "homepage"? The event list (public) or the admin dashboard?
* Do we have any caching technology being used to handle multiple views for a high volume site?
    * at the moment, there is a caching mechanism on the templates of the public area (see https://github.com/exteso/alf.io/blob/master/src/main/java/alfio/config/MvcConfiguration.java#L251 ) but we do not send cache headers on the client. What is your use case? 

Cheers,
Celestino

**Comment by rudboruah** [comment]
Hwy Celestino,

Thanks for your quick reply. Much appreciated and WELL DONE guys!

Admin section took me some time to get around but I did manage to add organizations, add events and test out emails. I have not tested Stripe yet. Cool that you guys are on it.

1. What I mean is a Event Search facility in the public homepage and not admin dashboard. e.g homepage of https://www.coursera.org/ from the public homepage? If this doesnot exist we may have to create this by making calls to the Java Platform?
2. Full Page Cache: Use Case is to handle 500 client visits/ Search at any point in time with an event catalog of 1000 events. We do not want the Java Engine to pull it out from the Database all the time and hence if we cache full page htmls and the urls, we may be able to increase efficiency. Do you guys support full page Cache?
3. Do you have any other template for the public homepages to list the events, catalogs etc?
4. General one ;) Why Java and not the technologies like Ruby/ NodeJS or / LAMP that require less resources than Java and cheaper human resources to maintain?

Do I make any sense? 

Thanks,
Dhruv

**Comment by cbellone** [comment]
Hi Rud,

2016-01-07 0:53 GMT+01:00 rudboruah <notifications@github.com>:

> Hwy Celestino,
>
> Thanks for your quick reply. Much appreciated and WELL DONE guys!
>
> Admin section took me some time to get around but I did manage to add
> organizations, add events and test out emails. I have not tested Stripe
> yet. Cool that you guys are on it.
>
>    1. What I mean is a Event Search facility in the public homepage and
>    not admin dashboard. e.g homepage of https://www.coursera.org/ from
>    the public homepage? If this doesnot exist we may have to create this by
>    making calls to the Java Platform?
>
> there are REST APIs available. These APIs are not yet documented, sorry
for that. Anyway, using these APIs you can implement your own front-end
with all the features you need for listing, filtering and caching the
events. And since we expose CORS headers for that, you can develop widgets
and/or dedicated pages directly on your website(s) using the technologies
that you're more familiar with.

Once the user selects an event, for security reasons, he/she must be
redirected to the alf.io instance for the next steps.

The APIs are:
GET https://<alf.io-address>/api/events (returns all the events registered
on the system. In your case, 1000)
GET https://<alf.io-address>/api/events/<event-key> (returns the details of
a single event)

how does it sound?


>
>    1. Full Page Cache: Use Case is to handle 500 client visits/ Search at
>    any point in time with an event catalog of 1000 events. We do not want the
>    Java Engine to pull it out from the Database all the time and hence if we
>    cache full page htmls and the urls, we may be able to increase efficiency.
>    Do you guys support full page Cache?
>
> I think that the solution above could solve 3/4 of your worries.
Implementing your own cache would be a perfect integration, wouldn't be? We
would be very happy if you could share the results...
Anyways we are currently running performance tests, we'll publish result
(and fix related bottlenecks) asap.

>
>    1. Do you have any other template for the public homepages to list the
>    events, catalogs etc?
>
> no, see above

>
>    1. General one ;) Why Java and not the technologies like Ruby/ NodeJS
>    or / LAMP that require less resources than Java and cheaper human resources
>    to maintain?
>
> I don't want to start a flame-war here, really. I'm not the right person
for that :-)
Jokes aside, Why java? Because we deeply know it, and IMHO "ease to
maintain" is just a matter of familiarity/confidence, isn't it?

WDYT?

Celestino

**Comment by rudboruah** [comment]
Thanks a lot Celestino for all your comments and help. We will be following your product closely.

**Comment by cbellone** [comment]
OK, thank you. I really hope that one day it could help you to build your service.
I guess that it is safe to close this issue now.
Cheers!
